modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/LimonBlaze/thermorigins/issues"
[[mods]]
modId="thermorigins"
version="${version}"
displayName="Thermorigins"
#updateJSONURL=""
displayURL="https://github.com/LimonBlaze/thermorigins"
logoFile="pack.png"
authors="LimonBlaze"
description='''
A Forge add-on for the Origins mod
'''

[[dependencies.thermorigins]]
    modId="forge"
    mandatory=true
    versionRange="[40.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.thermorigins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.thermorigins]]
    modId="origins"
    mandatory=true
    versionRange="[1.18.2-1.5,)"
    ordering="NONE"
    side="BOTH"
